apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
    type: backend
spec:
  type: NodePort
  ports:
    - targetPort: 5000
      port: 80
      nodePort: 30005
  selector:
      type: backend